### ISSUE TITLE
error running on test data

### ISSUE THREAD

**Issue by amelieff-pub** [fanglab/SMALR#2]
Dear SMALR developers,

I have some trouble excuting analysis on test data.
I was wondering if you could tell me what's wrong.

I followed your instructions to install SMALR pipeline,
except I had to install nose and hdf5 in advance.

I'm using CentOS 6.3, Python2.7.

```
$ ./run_test_SMp.sh                                                                                                                         /home/smrtanalysis/SMALR_test/SMALR/test
Traceback (most recent call last):
  File "/home/smrtanalysis/SMALR_test/smalr_venv/bin/call_smalr.py", line 4, in <module>
    __import__('pkg_resources').run_script('smalr==1.0.0', 'call_smalr.py')
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/EGG-INFO/scripts/call_smalr.py", line 5, in <module>
    sys.exit(main())
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 86, in main
    sys.exit( app.run() )
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 60, in run
    self.check_contig_names( nat_contigs )
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 52, in check_contig_names
    raise Exception("%s in %s not found in %s!" % (name, self.Config.ref, self.Config.native_cmph5))
Exception: scf7180000000008 in /home/smrtanalysis/SMALR_test/SMALR/test/HP_J99_HGAP2.fasta not found in /home/smrtanalysis/SMALR_test/SMALR/test/nat_longlib.cmp.h5!
```

```
$ ./run_test_SMsn.sh                                                                                                                       /home/smrtanalysis/SMALR_test/SMALR/test  1
Preparing to iterate over all contigs in /home/smrtanalysis/SMALR_test/SMALR/test/nat_shortlib.cmp.h5
    - ref000001 (J99)
11:40:32 [INFO]
11:40:32 [INFO] ====================================
11:40:32 [INFO] Analyzing contig ref000001 (J99)
11:40:32 [INFO] ====================================
11:40:32 [INFO] ref000001 - contig_id:               ref000001
11:40:32 [INFO] ref000001 - contig_name:             J99
Traceback (most recent call last):
  File "/home/smrtanalysis/SMALR_test/smalr_venv/bin/call_smalr.py", line 4, in <module>
    __import__('pkg_resources').run_script('smalr==1.0.0', 'call_smalr.py')
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/EGG-INFO/scripts/call_smalr.py", line 5, in <module>
    sys.exit(main())
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 86, in main
    sys.exit( app.run() )
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr_multicontig.py", line 81, in run
    runner.run()
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr.py", line 332, in run
    self.find_motif_sites()
  File "/home/smrtanalysis/SMALR_test/smalr_venv/lib/python2.7/site-packages/smalr-1.0.0-py2.7.egg/smalr/smalr.py", line 206, in find_motif_sites
    raise Exception("Couldn't write the contig-specific fasta file!")
Exception: Couldn't write the contig-specific fasta file!
```

```
$ ls -lha                                                                                                                                   /home/smrtanalysis/SMALR_test/SMALR/test
drwxrwxr-x.  3 mi mi 4.0K  6 22 11:40 2016 .
drwxr-xr-x. 10 mi mi 4.0K  6 20 19:39 2016 ..
-rw-rw-r--.  1 mi mi 1.8M  6 20 12:03 2016 HP_J99_HGAP2.fasta
-rw-r--r--.  1 mi mi 1.7M  6 22 11:39 2016 HP_J99_HGAP2.fasta.tmp
-rw-rw-r--.  1 mi mi 1.6M  6 20 12:03 2016 Hpylori_J99.fasta
-rw-r--r--.  1 mi mi    0  6 22 11:40 2016 Hpylori_J99.fasta.tmp
drwxr-xr-x.  2 mi mi 4.0K  6 22 11:40 2016 J99_SMsn
-rw-rw-r--.  1 mi mi  23M  6 20 12:03 2016 J99_nat_CCS.fastq
-rw-rw-r--.  1 mi mi  118  6 20 12:03 2016 input_SMp.txt
-rw-rw-r--.  1 mi mi  132  6 20 12:03 2016 input_SMsn.txt
-rw-rw-r--.  1 mi mi  27M  6 20 12:03 2016 nat_longlib.cmp.h5
-rw-rw-r--.  1 mi mi 4.6M  6 20 12:03 2016 nat_shortlib.cmp.h5
-rwxrwxr-x.  1 mi mi   82  6 20 12:03 2016 run_test_SMp.sh
-rwxrwxr-x.  1 mi mi   92  6 20 12:03 2016 run_test_SMsn.sh
-rw-rw-r--.  1 mi mi  34M  6 20 12:03 2016 wga_longlib.cmp.h5
-rw-rw-r--.  1 mi mi  15M  6 20 12:03 2016 wga_shortlib.cmp.h5
```

Thanks!

**Comment by tay45** [comment]
Hello,

I have the same issue.. Thanks!

**Comment by timp0** [comment]
Same issue here as well.

**Comment by jbeaulaurier** [comment]
Hello all, sorry you are having an issue. Just to clarify so that I can try to reproduce this error, are you all running CentOS and Python 2.7?

**Comment by jbeaulaurier** [comment]
Hi all-

I believe I have fixed the issue, which had to do with how contig names are parsed from the cmp.h5 files. Please let me know if you still have problems running the code on the test data provided.

Thanks,
John
